import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#005EB8',
        'on-primary': '#ffffff',
        'primary-container': '#005eb8',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#a9c7ff',
        'on-primary-fixed': '#001b3d',
        'on-primary-fixed-variant': '#00468c',
        'on-primary-container': '#c8daff',
        secondary: '#006a6a',
        'on-secondary': '#ffffff',
        'secondary-container': '#8cf3f3',
        'on-secondary-container': '#007070',
        'secondary-fixed': '#8cf3f3',
        'secondary-fixed-dim': '#6fd7d6',
        'on-secondary-fixed': '#002020',
        'on-secondary-fixed-variant': '#004f4f',
        tertiary: '#940010',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#bb1b21',
        'on-tertiary-container': '#ffceca',
        'tertiary-fixed': '#ffdad6',
        'tertiary-fixed-dim': '#ffb3ac',
        'on-tertiary-fixed': '#410003',
        'on-tertiary-fixed-variant': '#930010',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#f3faff',
        'on-surface': '#071e27',
        'surface-variant': '#cfe6f2',
        'on-surface-variant': '#424752',
        'surface-container': '#dbf1fe',
        'surface-container-low': '#e6f6ff',
        'surface-container-high': '#d5ecf8',
        'surface-container-highest': '#cfe6f2',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#c7dde9',
        'surface-bright': '#f3faff',
        'surface-tint': '#005eb8',
        outline: '#727783',
        'outline-variant': '#c2c6d4',
        'inverse-surface': '#1e333c',
        'inverse-on-surface': '#dff4ff',
        'inverse-primary': '#a9c7ff',
        background: '#f3faff',
        'on-background': '#071e27',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};

export default config;
